### ISSUE TITLE
Guide on self hosting

### ISSUE THREAD

**Issue by iamchathu** [grafbase/grafbase#1152]
**Describe the solution you'd like**
Is this project can be self hosted completely. Or is it mandatory to use the cloud service offering?

**Additional context**
I saw self hostable in the home page but I couldn't find any guide on it. I'm sorry if there is currently a guide but if I can not find it.

**Comment by fbjork** [comment]
Hi @iamchathu! 
The Grafbase Engine can be run self-hosted as shown in the changelog example: https://grafbase.com/changelog/self-host#get-started

Let me know if you have specific questions or feature requests. We will add a proper guide and docs over the coming weeks!
