### ISSUE TITLE
Grafbase Initialization with trypescript "error: unexpected argument '--config-format' found"

### ISSUE THREAD

**Issue by axiskafi** [grafbase/grafbase#1153]
When i tried to initialize the graphbase with typescript every time i am getting this error

npx grafbase init --config-format typescript
**error: unexpected argument '--config-format' found**
tip: to pass '--config-format' as a value, use '-- --config-format'

if i follow the suggested tip the it throws me another error
npx grafbase init -- -
-config-format typescript
**error: unexpected argument 'typescript' found**

My CLI version is 0.51.0

- OS: macOS
- Version Ventura 13.0

My package.json file
{
  "name": "collection",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "@headlessui/react": "^1.7.17",
    "@types/jsonwebtoken": "^9.0.5",
    "cloudinary": "^1.41.0",
    "dotenv": "^16.3.1",
    "graphql-request": "^6.1.0",
    "jsonwebtoken": "^9.0.2",
    "next": "14.0.4",
    "next-auth": "^4.24.5",
    "react": "^18",
    "react-dom": "^18",
    "type-fest": "^4.8.3"
  },
  "devDependencies": {
    "@grafbase/sdk": "^0.13.1",
    "@types/node": "^20",
    "@types/react": "^18",
    "@types/react-dom": "^18",
    "autoprefixer": "^10.0.1",
    "eslint": "^8",
    "eslint-config-next": "14.0.4",
    "postcss": "^8",
    "tailwindcss": "^3.3.0",
    "typescript": "^5"
  }
}

**Comment by yoav-lavi** [comment]
@axiskafi Hey!
We've recently removed SDL from `init`, so running it without the flag will produce TypeScript.

Let me know if this doesn't work!
