### ISSUE TITLE
Github authentication on creating a new project

### ISSUE THREAD

**Issue by Shammahkahangi** [grafbase/grafbase#1189]
**Describe the bug**
I cant import my project

**To Reproduce**

**Expected behavior**

**Examples**
If applicable, add examples of input and output to help explain your problem.

**Desktop (please complete the following information):**

- OS: [e.g. macOS]
- Version [e.g. v0.11.0]

**Additional context**

**Comment by fbjork** [comment]
@Shammahkahangi can you attach a screenshot of what you're seeing?
