### ISSUE TITLE
Allow to inline returns without having to `g.ref` and `g.type` every time

### ISSUE THREAD

**Issue by nikitavoloboev** [grafbase/grafbase#1200]
**Describe the solution you'd like**

Currently when I make a resolver I have to do this:

```js
g.query("publicGetGlobalTopic", {
  args: { topicName: g.string() },
  returns: g.ref(
    g.type("publicGetGlobalTopicOutput", {
      prettyName: g.string(),
      topicSummary: g.string(),
      latestGlobalGuide: g.ref(latestGlobalGuide).optional(),
      links: g.ref(GlobalLink).list(),
      notesCount: g.int()
    })
  ),
  resolver: "public/getGlobalTopic"
})
```

I find it very annoying having to write this part every time 

```
g.ref(
    g.type("publicGetGlobalTopicOutput", {`
```

I wish I could do this:

```js
g.query("publicGetGlobalTopic", {
  args: { topicName: g.string() },
  returns: {
    prettyName: g.string(),
    topicSummary: g.string(),
    latestGlobalGuide: g.ref(latestGlobalGuide).optional(),
    links: g.ref(GlobalLink).list(),
    notesCount: g.int()
  },
  resolver: "public/getGlobalTopic"
})
```

Similar to how `args: ` already works. 

Reasoning is that, I find it time consuming having to write out a unique name for `g.type` every time for a type that will never be reused. It's an output of resolver. It's not meant to be reused.

**Additional context**

In [my grafbase config](https://github.com/learn-anything/learn-anything.xyz/blob/dev/grafbase/grafbase.config.ts) I have 11 matches of this repetition, only there to make grafbase happy.

<img width="1512" alt="image" src="https://github.com/grafbase/grafbase/assets/6391776/154bdb49-588e-4c43-879e-1cfc2c564855">

**Comment by fbjork** [comment]
@nikitavoloboev every query needs a return type so there's no way to get around that.

**Comment by tomhoule** [comment]
Yes the return type has to have a name (every GraphQL type has a name). You can still shorten things a bit with a helper like `const referenceAdHoc = (name, definition) => g.ref(g.type(name, definition))`.
