### ISSUE TITLE
Allow setting default account to open in Grafbase dashboard

### ISSUE THREAD

**Issue by nikitavoloboev** [grafbase/grafbase#1201]
**Describe the solution you'd like**

Currently when I open https://grafbase.com/dashboard

I see:

<img width="761" alt="image" src="https://github.com/grafbase/grafbase/assets/6391776/6faf534a-e879-41a8-af97-2c5713ac1d94">

`Nikita` account gets opened but I want by default for my organisation `learn-anything` to open.

One way to achieve this is perhaps allow users to rearrange the order of the accounts, the top one will be the one that gets opened in `dashboard`.

**Comment by fbjork** [comment]
@nikitavoloboev what if we remembered the last account used and navigate to that once you access the `/dashboard` path?

**Comment by nikitavoloboev** [comment]
That would work for me too.

**Comment by fbjork** [comment]
@nikitavoloboev the dashboard now remembers the last account used. Thanks for the suggestion!
