### ISSUE TITLE
Add full drain log support to be able to use Baselime for full observability into Grafbase

### ISSUE THREAD

**Issue by nikitavoloboev** [grafbase/grafbase#1202]
**Describe the solution you'd like**

The current logs provided by Grafbase are lacking a lot.

<img width="1496" alt="image" src="https://github.com/grafbase/grafbase/assets/6391776/e7e0aa4b-647f-4e25-91ec-94168fe31c1a">

No way to group by resolver nicely, no way to see the issues that happened in resolver fast etc. Currently I ignore all logs because I find it useless to go to the `/logs` page in dashboard.

What I want is ability to pipe all logs/errors and in which resolvers those logs/errors happened in to [Baselime](https://baselime.io).

So if you take this resolver for example:

<img width="461" alt="image" src="https://github.com/grafbase/grafbase/assets/6391776/7e381f24-df44-4d9d-936e-373ff21cfcc1">

If `throw new GraphQLError` gets triggered, I get the time it got triggered in, in which resolver and what logs happened right before the resolver triggered `console.error(err)` in my case. Baselime does a good job at letting you search and organise logs, I just need ability to ingest all this Grafbase data and pipe it into Baselime. 

Baselime has deep support for Cloudflare Workers now, perhaps use that to make the integration even nicer.

https://twitter.com/boristane/status/1717590624596083046

**Comment by fbjork** [comment]
Now that Baselime is part of Cloudflare we won't be implementing this, but we do support Datadog today.
