### ISSUE TITLE
Authorizer Authentication not working, not called

### ISSUE THREAD

**Issue by pczern** [grafbase/grafbase#1203]
**Describe the bug**
Authorizer is not called, console.error does not log in verbose mode (-v)

**To Reproduce**
Do grafbase init
put an Authorizer in `grafbase/auth/authorizer.ts`
```tsx
export default function ({ request }) {
  const { headers } = request
console.error('log')
return false;
}
```
run with `grafbase dev`

**Expected behavior**
I expected the graph to be inaccessible and the logging to occur because I have not returned group `g1`
```tsx
export default config({
  graph: g,
  auth: {
    providers: [authorizer],
    rules: (rules) => {
      rules.groups(['g1'])
    },
  },
})
```

**Additional context**
Followed documentation from here https://grafbase.com/docs/auth/providers

**Comment by fbjork** [comment]
@pczern be sure not to pass the x-api-key header when you're testing this locally (Pathfinder sends an empty one by default). Otherwise it bypasses the authorizer.

**Comment by pczern** [comment]
@fbjork I have created a minimal reproduction with [Codesandbox](https://codesandbox.io/p/devbox/grafbase-reprod-rtfh87?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clr822bjo00072e66286uceuf%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clr822bjo00022e66j0mm42rt%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clr822bjo00042e6614b7gbaj%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clr822bjo00062e66fei6sgki%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clr822bjo00022e66j0mm42rt%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clr822bjo00012e669ivnuvxt%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%257D%255D%252C%2522id%2522%253A%2522clr822bjo00022e66j0mm42rt%2522%252C%2522activeTabId%2522%253A%2522clr822bjo00012e669ivnuvxt%2522%257D%252C%2522clr822bjo00062e66fei6sgki%2522%253A%257B%2522id%2522%253A%2522clr822bjo00062e66fei6sgki%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A4000%252C%2522id%2522%253A%2522clr82a2in00qs2e664x2bgvqg%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clr82a2in00qs2e664x2bgvqg%2522%257D%252C%2522clr822bjo00042e6614b7gbaj%2522%253A%257B%2522id%2522%253A%2522clr822bjo00042e6614b7gbaj%2522%252C%2522activeTabId%2522%253A%2522clr822uqo00682e660p2ahc0f%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clr822bjo00032e66vz2yykpc%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%257D%252C%257B%2522id%2522%253A%2522clr822uqo00682e660p2ahc0f%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clr822vx80012edcudb6yhsq7%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by fbjork** [comment]
@pczern thanks for sending the sandbox, but it seems the be stuck when we try to access it. Mind pinging me in Discord so we can troubleshoot it together?
