### ISSUE TITLE
Env variables in authorizer

### ISSUE THREAD

**Issue by pczern** [grafbase/grafbase#1204]
**Describe the solution you'd like**
Add environment variables to Authorizer function or provide access via library.

**Additional context**
It looks like I have to init a graph first in an authorizer, before I can get any environment variables.
```
import { auth, graph, config, connector } from '@grafbase/sdk'
const g = graph.Standalone()
g.env('env-variable')
```

**Comment by fbjork** [comment]
@pczern you can access environment variables in authorizers using `process.env`. Have you tried that?
