### ISSUE TITLE
Deploy Command doesn't use GRAFBASE_ACCESS_TOKEN

### ISSUE THREAD

**Issue by rawkode** [grafbase/grafbase#1388]
**Describe the bug**

In a CI/CD workflow, I am providing the `GRAFBASE_ACCESS_TOKEN` environment variable as directed by the documentation; but I am receiving the following error:

```
🕒 Your project is being deployed...
Error: could not complete a request: Server returned 401 Unauthorized: Unauthorized
```

**To Reproduce**
```
export GRAFBASE_ACCESS_TOKEN=""
grafbase deploy
```

**Expected behavior**
Deploy

**Comment by yoav-lavi** [comment]
Hey @rawkode, when testing this works correctly, could you please check your token and try `GRAFBASE_ACCESS_TOKEN="..." grafbase deploy` just to verify? Thanks

**Comment by yoav-lavi** [comment]
Closing for now, please reopen if this is still causing issues
