### ISSUE TITLE
Account Level Environment Variables

### ISSUE THREAD

**Issue by rawkode** [grafbase/grafbase#1392]
**Describe the solution you'd like**
Graph federation allows us to split up our API in many smaller components, which is fantastic. I've found while breaking an API up that I need to create the same environment variables for each graph.

The ability to set environment variables at the project level would minimise some of this toil.

**Comment by fbjork** [comment]
@rawkode great idea! I think you meant account level environment variables, right?

**Comment by fbjork** [comment]
environments will go away with standalone graphs
