### ISSUE TITLE
JWT Claim Forwarding

### ISSUE THREAD

**Issue by rawkode** [grafbase/grafbase#1393]
**Describe the solution you'd like**
Grafbase auth can handle verifying a JWT is valid before forwarding requests to subgraphs.

Unfortunately, it doesn't pass on these claims (such as sub, iss, groups). Instead, it passes on the header which requires a bit more work on the users part.

It would be ideal if Grafbase's router would provide the JWT claims within the context parameter.

**Comment by fbjork** [comment]
@rawkode great suggestions. Added to the roadmap!

**Comment by tobiastornros** [comment]
This would be awesome!

**Comment by ajosecueto** [comment]
i'm waiting for this feature, any news?, for now i will have todo decode each token inside subgraphs.

**Comment by tomhoule** [comment]
Hi @ajosecueto — it's implemented, just waiting for a review (https://github.com/grafbase/grafbase/pull/1695).

The claims will be available like in this example:

```js
export default function(_parent, _args, ctx) {
  const { jwtClaims, headers } = ctx.request

  // ...
}
```

**Comment by fbjork** [comment]
The latest Grafbase SDK was released today with support for JWT claims in the context:
https://grafbase.com/changelog/jwt-claims-in-resolver-context
