### ISSUE TITLE
Streaming Deployment Logs / Wait Flag

### ISSUE THREAD

**Issue by rawkode** [grafbase/grafbase#1410]
**Describe the solution you'd like**
I have automated my Grafbase deploy with Dagger, but I need to hardcode an arbitrary `sleep 600` to give the deployment time to rollout.

Ideally, I'd like to use `grafbase deploy --wait`, or even `grafbase deploy --logs`

**Comment by fbjork** [comment]
@rawkode this is now part of the latest Grafbase CLI. Thanks for the suggestion!
