### ISSUE TITLE
Realationship, Search and Rules does not exists 

### ISSUE THREAD

**Issue by Soheib-Kiani** [grafbase/grafbase#1492]
This is my problems through using these methods

grafbase.config.ts(11,15): error TS2339: Property 'relation' does not exist on type 'Graph'.
10:00:42.196
grafbase.config.ts(12,10): error TS7006: Parameter 'rules' implicitly has an 'any' type.
10:00:42.196
grafbase.config.ts(23,24): error TS2339: Property 'search' does not exist on type 'StringDefinition'.
10:00:42.196
grafbase.config.ts(24,16): error TS2339: Property 'relation' does not exist on type 'Graph'.
10:00:42.196
grafbase.config.ts(25,10): error TS7006: Parameter 'rules' implicitly has an 'any' type.
10:00:42.196
Failed to build the TypeScript config."

**Comment by fbjork** [comment]
Hi @Soheib-Kiani Could you paste your config file so we can see what's going on? Based on the errors it looks like you're using deprecated search and relations logic from the database feature that was sunset last year.

**Comment by Soheib-Kiani** [comment]
Yes I used old version. Now my application crashed because of these changes.
