### ISSUE TITLE
Cant connect to Supabase (postgres)

### ISSUE THREAD

**Issue by ZhymonNorman** [grafbase/grafbase#1794]
**Describe the bug**
Having issues connecting to Supabase, I receive the following error

`Error: Postgres data source: could not connect to Postgres: error performing TLS handshake: invalid peer certificate: UnknownIssuer`

**To Reproduce**
1. Create a Grafbase project via the CLI
2. Create a Supabase project
3. Grab the database URL from the Supabase project dashboard
4. Set the database URL in the env file
5. Start dev mode 

(this happens with local development and cloud deployments via the Grafbase dashboard)

**Expected behavior**
The grafbase project should start and connect to the postgres database

**Examples**
```
import { config, connector, graph } from '@grafbase/sdk'

const g = graph.Standalone()

const pg = connector.Postgres('Postgres', {
  url: g.env('DATABASE_URL'),
})

g.datasource(pg)

export default config({
  graph: g,
  auth: {
    rules: (rules) => {
      rules.public()
    }
  }
})
```

**Desktop**

- OS: `Ubuntu 22.04.4 LTS`
- Grafbase Version `Grafbase CLI 0.75.0`
- Supabase Postgres Version `15.1.1.64`

**Additional context**
- I have not enabled auth on the Supabase project. 
- SSL connections are not enforced in Supabase

**Comment by ZhymonNorman** [comment]
Found this thread in [Discord](https://discord.com/channels/890534438151274507/1185298428310331392/1185299059158822932) looks like this is due to a known Cloudflare limitation 


> This is due to cloudflare not yet supporting self-signed certificates. the database endpoint must have a real domain and must have a certificate from a provider such as let's encrypt for cloudflare to be able to connect. We've been having a lot of success with Neon as our database provider, which handles modern TLS pretty nicely. Later on when Cloudflare accepts passing certificates, we will naturally start supporting them too.

I attempted to use Railway as a provider instead and got a similar error. This happened locally and via the deployments dashboard. 

`16:15:11.197 could not connect to Postgres: error performing TLS handshake: invalid peer certificate: Other(OtherError(UnsupportedCertVersion))`

**Comment by fbjork** [comment]
> Found this thread in [Discord](https://discord.com/channels/890534438151274507/1185298428310331392/1185299059158822932) looks like this is due to a known Cloudflare limitation
> 
> > This is due to cloudflare not yet supporting self-signed certificates. the database endpoint must have a real domain and must have a certificate from a provider such as let's encrypt for cloudflare to be able to connect. We've been having a lot of success with Neon as our database provider, which handles modern TLS pretty nicely. Later on when Cloudflare accepts passing certificates, we will naturally start supporting them too.
> 
> I attempted to use Railway as a provider instead and got a similar error. This happened locally and via the deployments dashboard.
> 
> `16:15:11.197 could not connect to Postgres: error performing TLS handshake: invalid peer certificate: Other(OtherError(UnsupportedCertVersion))`
> 
> I ended up using Vercel Postgres for now (which is powered by Neon)

Yes, Neon or Vercel Postgres will work fine until Cloudflare supports self-signed certs or Railway/Supabase provide verified certificates.
