### ISSUE TITLE
Next js Example not working

### ISSUE THREAD

**Issue by amanr-dev** [grafbase/grafbase#1885]
Next JS's example in codesandbox is not working, showing an error "Network error".

## Screenshot
![Screenshot 2024-07-11 173307](https://github.com/grafbase/grafbase/assets/124811276/9b02fba7-dc05-4bf3-94d2-3656cc529965)

**Comment by fbjork** [comment]
@amanr-dev which example is this?

**Comment by amanr-dev** [comment]
> @amanr-dev which example is this?

Codesandbox link inside `/examples/nextjs`

**Comment by fbjork** [comment]
@amanr-dev Hi, thanks for reporting this issue.

This example is using the now deprecated database feature of Grafbase. We are in the process of updating all our examples a guides to reflect the current features of Grafbase. Will close this issue for now.
