### ISSUE TITLE
Cannot Query Nested Field

### ISSUE THREAD

**Issue by khaifahmi99** [grafbase/grafbase#192]
**Describe the bug**
Unable to query nested field from another model

**To Reproduce**
```
---> Schema
enum BillType {
  Electricity
  Gas
  Water
  Wifi
  Grocery
  Others
}

type Resident @model {
  id: ID!
  firstName: String!
  lastName: String!
  email: String! @unique
  phone: String
  dob: String
}

type Bill @model {
  id: ID!
  type: BillType!
  title: String!
  amount: Float!
  date: String!
  residents: [Resident!]!
  paid: Boolean!
  paidDate: String

  description: String

}

---> Query Request
query GetBills {
  billCollection(last: 7) {
    edges {
      node {
        id
        title
        residents(last: 5) {
          pageInfo {
            hasNextPage
          }
          edges {
            node {
              id
              firstName
            }
          }
        }
      }
    }
  }
}

---> Query Response
{
  "data": {
    "billCollection": {
      "edges": null
    }
  },
  "errors": [
    {
      "locations": [
        {
          "column": 9,
          "line": 7
        }
      ],
      "message": "Internal Error: Unknown argument '{name}'",
      "path": [
        "billCollection",
        "edges",
        0
      ]
    }
  ]
}
```

**Expected behavior**
Should return no error and appropriate nested data. This works fine if the query is done without the nested field (bill collection without residents) or residents collection

**Examples**
Refer to "Reproduce" section

**Desktop (please complete the following information):**

- OS: macOS Ventura
- Version 13.1

**Additional context**

**Comment by fbjork** [comment]
hi @khaifahmi99 thanks for reporting this issue. 

We've reproduced the problem and are working on a fix. 

Will let you know when the fix has been released.

**Comment by khaifahmi99** [comment]
Any time estimate on when this will be fixed?

**Comment by khaifahmi99** [comment]
Do I have to redeploy to get the cloud version working?

Also, without redeploying, I now received a different error message from the network response

`message : "Internal Error: Unknown argument 'orderBy'"`

**Comment by fbjork** [comment]
@khaifahmi99 at the moment you have to redeploy your project do resolve this issue. We are working on making platform upgrade seamless when we go into public beta. Please let us know if this resolves your issues!

**Comment by khaifahmi99** [comment]
Re-deploy solved the issue, thanks for the quick reply! 
The upgrade feature sounds like a great feature
