### ISSUE TITLE
Global Object Identification from PostgreSQL autoincrement

### ISSUE THREAD

**Issue by lambrosx77** [grafbase/grafbase#1957]
Hi,

I'm new with grafbase.

Is there an easy way to implement global object identifcation when database uses autoincrement as id (field could be named something like foobar_id)?

In other project like DGS, I prefix my ID with object name.

Without redefining all types or resolvers, could we have somenhing like for query and mutation?
```
const prefixId = (root) => {
  for (const key in root) {
    if (key.endsWith('Id') && typeof root[key] === 'number') {
      root[key] = `${key}-${root[key]}`;
    }
  }
  return root;
};
```

Could we imagine specifying database and/or schema using that feature? 

Did I miss it in documentation?

Thank you for the help.

**Comment by fbjork** [comment]
@lambrosx77 Hi there! Are you using one of the database connectors?
