### ISSUE TITLE
Cannot create relationship edge

### ISSUE THREAD

**Issue by khanakia** [grafbase/grafbase#1983]
Cannot create relationship edge

I am using Postgres connector and  I have roles and users table how do I create `user > role` ref there is no help in docs.

```ts
const roles = g.type('PgRoles', {
  id: scalar.id(),
  name: scalar.string(),
})


const users = g.type('PgUsers', {
  role: g.ref(roles),
})

g.extend('PgUsers', {
  role: {
    returns: g.ref(roles),
    resolver: 'fullname',  // it needs resolver but I want only reference
  },
})
```

```gql
query {
  pg {
    usersCollection(first: 1) {
      edges {
        node {
          id
          role {
            name
          }
        }
      }
    }
   
  }
}

```

**Comment by tomhoule** [comment]
Hi @khanakia! We'll double check but I think there is no mutation to create models with nested related models. You would have to use the role mutation directly to create a role (or role assignment, depending how you set up your database) with the correct userId.

**Comment by khanakia** [comment]
I do not want to create a role i want to query the users and their role that's it

anyway I am using Hasura now which works perfectly

**Comment by tomhoule** [comment]
Ah I misunderstood the issue, the problem is the line you left a comment on in the TS snippet, right? The whole type definitions are unnecessary if you do not have custom resolvers, the schema and relations are inferred from the database schema.

**Comment by khanakia** [comment]
Yes, I did not use the customer resolve but I am not enforcing the Foreign Key relationship in the database. 

So I want to create a virtual relationship just like Hasura does.

**Comment by tomhoule** [comment]
Yes that isn't supported with the postgres connector.

**Comment by khanakia** [comment]
I see thanks for the info
