### ISSUE TITLE
Documentation for the CLI is a bit outdated

### ISSUE THREAD

**Issue by icepuma** [grafbase/grafbase#1989]
**Describe the bug**
https://grafbase.dev/docs/cli#installing contains instructions that I could install the CLI via `cargo install grafbase`, but https://crates.io/crates/grafbase is pretty outdated :)

**To Reproduce**
`cargo install grafbase` and then `grafbase --version`

**Expected behavior**
Remove the instructions for the `cargo` path.

**Comment by icepuma** [comment]
I couldn't find the sources for the documentation otherwise I would've contributed the change via PR :)

**Comment by fbjork** [comment]
Thanks for reporting! I just updated the docs to remove cargo install since it's not updated any more.
