### ISSUE TITLE
[Question] How can I set an auth rule based on a custom field value?

### ISSUE THREAD

**Issue by nandotess** [grafbase/grafbase#223]
### Use Case

I would like to allow the `get` operation only for the authorized user (active session) and not for all users.

Example: I'm logged in, and I would like to only be able to `get` myself and not any other user.

My code is already only making requests of the user from the active session, but if the database can prevent this to happen as well, it would be a security improvement to prevent any user to try to query a different user that it's not himself.

### Current Code

```
schema
	@auth(
		providers: [{ type: oidc, issuer: "{{ env.CLERK_ISSUER_URL }}" }]
		rules: [
			{ allow: private, operations: ["get"] }
			{ allow: groups, groups: ["admin"] }
		]
	) {
	query: Query
}
```

Apologize if this is already implemented and I don't know how to do it. But I couldn't find any way to get in touch with the support, and searching the documentation I didn't find any way to do this.

Thank you!

**Comment by notrab** [comment]
Hey @nandotess 👋🏻 

That's a great question. It's something we're working on next that we're calling "owner based auth".

Here's a quick look at what it could end up looking like (notice `owner`):

```gql
schema
  @auth(
    providers: [{ type: oidc, issuer: "https://idp.example.com" }]
    rules: [
      { allow: private, operations: [read] },
      { allow: groups, groups: ["admin"] }, # full access
      { allow: owner, operations: [create, update] } # create, update, get, list for document owner
    ]
  ) {
  query: Query
}
```

As always we will allow this to be done at a model and field level:

```gql
type Todo @model @auth(rules: [{ allow: owner }]) {
  description: String
  owner: String @auth(rules: [{ allow: owner, operations: [read, delete] }])
}
```

We will design this in a way that allows documents to have multiple owners in the future.

I'll close this "issue" but I'd love for you to join us in Discord if you aren't already so we can invite you to try this out as soon as it lands.
