### ISSUE TITLE
[Bug] Why do I see/receive so many CORS error when loading the data on the frontend/browser?

### ISSUE THREAD

**Issue by nandotess** [grafbase/grafbase#226]
**Describe the bug**
Why do I see/receive so many CORS error when loading the data on the frontend/browser? It's happening constantly during my development.

**To Reproduce**
- Access a page that loads the data using Apollo Client (see more [here](https://github.com/grafbase/grafbase/issues/225))
- ~30% of the time I'm getting 500 error (CORS)
  - Most common on first and second tries, after the server/service is "warn" I don't get the error anymore

**Expected behavior**
To have a solid/smooth experience when fetching data.

**Example (error)**

![image](https://user-images.githubusercontent.com/804109/222874556-59e31f37-9d9e-4e15-ba9c-35657a321092.png)

General:
- Request URL: https://nucona-main-nucona.grafbase.app/graphql
- Request Method: POST
- Status Code: 500 
- Referrer Policy: strict-origin-when-cross-origin

Request headers:
- authority: nucona-main-nucona.grafbase.app
- :method: POST
- :path: /graphql
- :scheme: https
- accept: */*
- accept-encoding: gzip, deflate, br
- accept-language: en-US,en;q=0.9
- authorization: Bearer ...
- cache-control: no-cache
- content-length: 527
- content-type: application/json
- origin: https://admin-portal-nucona.vercel.app
- pragma: no-cache
- referer: https://admin-portal-nucona.vercel.app/
- sec-ch-ua: "Chromium";v="110", "Not A(Brand";v="24", "Google Chrome";v="110"
- sec-ch-ua-mobile: ?0
- sec-ch-ua-platform: "macOS"
- sec-fetch-dest: empty
- sec-fetch-mode: cors
- sec-fetch-site: cross-site
- user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36

Response headers:
- alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400
- cf-ray: 7a2720b22fb43fdf-YYZ
- content-length: 20
- date: Sat, 04 Mar 2023 03:45:40 GMT
- server: cloudflare
- vary: Accept-Encoding

**Example (success)**

General:
- Request URL: https://nucona-main-nucona.grafbase.app/graphql
- Request Method: POST
- Status Code: 200 
- Remote Address: [2606:4700::6812:1571]:443
- Referrer Policy: strict-origin-when-cross-origin

Request headers:
- :authority: nucona-main-nucona.grafbase.app
- :method: POST
:- path: /graphql
- :scheme: https
- accept: */*
- accept-encoding: gzip, deflate, br
- accept-language: en-US,en;q=0.9
- authorization: Bearer ...
- cache-control: no-cache
- content-length: 527
- content-type: application/json
- origin: http://localhost:4200
- pragma: no-cache
- referer: http://localhost:4200/
- sec-ch-ua: "Chromium";v="110", "Not A(Brand";v="24", "Google Chrome";v="110"
- sec-ch-ua-mobile: ?0
- sec-ch-ua-platform: "macOS"
- sec-fetch-dest: empty
- sec-fetch-mode: cors
- sec-fetch-site: cross-site
- user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36

Response headers:
- access-control-allow-headers: Accept,Authorization,Cache-Control,Content-Type,Origin,X-Api-Key,X-Requested-With
- access-control-allow-methods: GET,OPTIONS,POST
- access-control-allow-origin: *
- access-control-max-age: 86400
- alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400
- cf-ray: 7a272a0838aca241-YYZ
- content-length: 560
- content-type: application/json, application/json;charset=UTF-8
- date: Sat, 04 Mar 2023 03:52:03 GMT
- server: cloudflare
- vary: Accept-Encoding
- x-grafbase-branch: main
- x-grafbase-environment: production
- x-grafbase-gateway-version: 2023-02-17
- x-grafbase-projectid: 01GRMTM39011DEA6QMGKD481PC

**Desktop (please complete the following information):**

- OS: macOS
- Version 12.5.1

**Additional context**
I can provide access to the private repo if required. Or even the app itself so you can test in your browser.

Thank you for the support & amazing product!

**Comment by notrab** [comment]
Hey @nandotess 👋🏻 

Thanks for the detailed report ❤️. This is certainly not ideal and something we'd be frustrated at too while building locally.

I am curious if this also occurs when working with Grafbase locally via the [CLI](https://grafbase.com/cli)? 

We recommend when building locally to use `npx grafbase dev` where possible. I want to make sure that experience is great too so please let us know if you see errors there also.

Nevertheless, we're looking into the issue you reported and will report back. I am certain the issues you face in development with the production URL can be removed altogether by using the Grafbase CLI.

**Comment by notrab** [comment]
Please ping me on Discord with an API key so I can try this out too. I'm curious to know if this error is shown more/less when using the `Authorization` vs `x-api-key` headers.

`x-api-key` shouldn't be used in production but for the purposes of debugging, this would be useful.

**Comment by notrab** [comment]
Hey @nandotess

Is this still an issue? I think we changed some things internally but curious if you still hit this error.

**Comment by nandotess** [comment]
All good, @notrab . Thank you!
