### ISSUE TITLE
Unable to run inside Visual Studio Code Dev Containers

### ISSUE THREAD

**Issue by andykenward** [grafbase/grafbase#354]
**Describe the bug**
Unable to run any commands via `npx grafbase` when working inside a ["Visual Studio Code Dev Containers"](https://code.visualstudio.com/docs/devcontainers/containers)

The below error happens.
```
node ➜ /workspaces/grafbase-with-nextjs (master) $ npx grafbase login
Need to install the following packages:
  grafbase@0.18.13
Ok to proceed? (y) y
/home/node/.npm/_npx/40adf13dbad12f93/node_modules/.bin/grafbase: 1: This: not found
```

**To Reproduce**

Follow the [Getting Started](https://code.visualstudio.com/docs/devcontainers/containers#_getting-started) guide for using Visual Studio Code Dev Containers. Once setup try using `grafbase` inside one of their predefined images.

I've only tried
- [`mcr.microsoft.com/devcontainers/base:ubuntu`](https://github.com/microsoft/vscode-dev-containers/tree/main/containers/ubuntu)
- [`mcr.microsoft.com/devcontainers/typescript-node:0-18`](https://github.com/microsoft/vscode-dev-containers/tree/main/containers/typescript-node)

**Expected behavior**
Be able to use `grafbase` within a container.

**Desktop:**

- OS: macOS
- Version 13.3.1
- VSCode 1.78.1
- Docker 4.19.0
- Node 18.16.0 arm64
- NPM 9.5.0
- Grafbase 0.18.13

**Comment by notrab** [comment]
Thanks for the issue @andykenward. We're tracking this internally and will get back to you. cc @yoav-lavi

**Comment by yoav-lavi** [comment]
Hey @andykenward, it's likely that what's happening is that an Linux arm64 container is being used (which our CLI does not support at the moment, we support `aarch64-apple-darwin`, `x86_64-apple-darwin`, `x86_64-pc-windows-msvc` and `x86_64-unknown-linux-musl`) but I'll be able to look a bit more into this issue soon.

What's your use case for dev containers?

**Comment by andykenward** [comment]
@yoav-lavi I thought that might have been the case. Thank you for looking into it. Would be great if there was a meaningful error message as the fallback for unsupported CPU architecture for users.

> What's your use case for dev containers?

I use Dev Containers in my local workflow when switching between projects. This also allows me to use a [GitHub Codespace](https://github.com/features/codespaces) in the browser.

The issue isn't present when using the same Dev Container [mcr.microsoft.com/devcontainers/typescript-node:0-18](https://github.com/microsoft/vscode-dev-containers/tree/main/containers/typescript-node) on a [GitHub Codespace](https://github.com/features/codespaces) as it chose to use `x64`. Where as my local machine would use `arm64`.

I expect other Cloud based code editors would also be using `x64` as the default.

**Comment by yoav-lavi** [comment]
@andykenward That is in fact a bug, we have a postinstall script that should error with ``'${targetTriple}' is currently unsupported`` in that case, but it either didn't or `npx` supresses postinstall errors. We'll investigate regardless of looking into possibly supporting AArch64 Linux.

Thank you!

**Comment by yoav-lavi** [comment]
We'll support arm64 Linux in one of our upcoming releases, will update you here when it comes out. I've confirmed that it works on VSCode dev containers

**Comment by yoav-lavi** [comment]
arm64 is supported in version 0.25.0, please let us know if you're still seeing any issues!
