### ISSUE TITLE
Data Fetching Forever

### ISSUE THREAD

**Issue by khaifahmi99** [grafbase/grafbase#389]
**Describe the bug**
From a web application (React), making a request to the graphql endpoint loads forever (shows as "Pending") and will never resolve. This is an already deployed endpoint and I can verify that it was working two weeks ago. This behaviour was first seen on 21 May 2023.

**To Reproduce**
This can be seen when making request via web network request or via Grafbase Pathfinder page (The UI shows **Introspecting Schema** loading state). Inside the network tab Dev Console, the request to the graphql endpoint  status is **(pending)**

**Expected behavior**
Network request should be resolved and not pending forever.

**Desktop (please complete the following information):**

- OS: MacOS Ventura
- Version: 13.3.1 (a) (22E772610a)

**Comment by obmarg** [comment]
Hi @khaifahmi99 - sorry for the delay getting back to you.  I think we were having an issue on production at the time you raised this issue, the symptoms of which are very similar to what you describe.  Is this working for you now?

**Comment by notrab** [comment]
I'll go ahead and close this for now @khaifahmi99 but if it continues to be an issue, let us know.

We recently rolled out some changes to Pathfinder that should resolve some of the earlier issues you faced.
