### ISSUE TITLE
Unable to use a defined union in a typescript schema config

### ISSUE THREAD

**Issue by pillowsoft** [grafbase/grafbase#509]
I can't seem to figure out how to use a defined union in the typescript config. It would appear we need a `unionRef` as we have similarly for Inputs (`inputRef`) and Enums (`enumRef`)

**To Reproduce**
Create a union definition in a typescript config, i.e.:

```ts

const locationContent = g.type('LocationContent', {
  longitude: g.float(),
  latitude: g.float(),
});

const imageContentType = g.type('ImageContent', {
  url: g.url(),
});

const contentType = g.union('Content', {
  imageContentType,
  locationContent
});
```

and now use it as a field in a model, i.e.:

```ts
const something = g
  .model('Something', {
    stuff: g.ref(contentType)
  });

```

**Expected behavior**
I would expect the schema to build and have a union in it. What I get is an error:

```
Argument of type 'Union' is not assignable to parameter of type 'Type'.
  Type 'Union' is missing the following properties from type 'Type': _name, fields, interfaces, field, and 2 more.
```

What am I missing? How do we use a union as a type for a field in a model?

Thanks!

**Comment by pimeys** [comment]
For now we do not support unions in model fields at all. The SDK will have the correct typing when the union support in the database side of things is implemented.
