### ISSUE TITLE
Custom subscription resolvers.

### ISSUE THREAD

**Issue by pillowsoft** [grafbase/grafbase#510]
**Describe the solution you'd like**

Custom subscription resolvers.

I see there is the ability to create custom query and mutation resolvers, but I don't see any capability to do that for subscriptions. My example is taking the ChatGPT example that you have in the repo and rather than awaiting the final text from the completion, allow using the OpenAI API streaming capabilities to provide a `live` updated response through a custom subscription resolver.

A possible workaround is to create a ChatGTP `answers` model and have the custom resolver using ChatGPT, do a mutation on the `answers` model, and then subscribe the client to that. Is it reasonable to do that? I.e. call back out to *GrafBase* with a mutation, inside a custom resolver?

**Comment by fbjork** [comment]
@pillowsoft We are planning to implement support for the `@stream` directive soon. Would that work for this use case?
