### ISSUE TITLE
npx grafbase init --config-format typescript, npx grafbase dev, npx grafbase init not working

### ISSUE THREAD

**Issue by mdamapong** [grafbase/grafbase#516]
**Describe the bug**

The error message I encountering suggests that there's an issue with the command I'm trying to run: npx grafbase init --config-format typescript. It appears that the command is not being recognized as a valid command by my system.

I ran npm install -g grafbase but still not wokring

**Expected behavior**
I should be getting pre made schema grafbae.config.ts
**Desktop (please complete the following information):**

- OS: MacOS
- Version V.13.01

**Additional context**
"dependencies"
    "@headlessui/react": "^1.7.15",
    "@types/jsonwebtoken": "^9.0.2",
    "@types/node": "20.4.0",
    "@types/react": "18.2.14",
    "@types/react-dom": "18.2.6",
    "autoprefixer": "10.4.14",
    "cloudinary": "^1.37.3",
    "dotenv": "^16.3.1",
    "graphql-request": "^6.1.0",
    "jsonwebtoken": "^9.0.1",
    "next": "13.4.9",
    "next-auth": "^4.22.1",
    "postcss": "8.4.25",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "tailwindcss": "3.3.2",
    "type-fest": "^3.12.0",
    "typescript": "5.1.6"
  
  "devDependencies"
    "@grafbase/sdk": "^0.1.1"

**Comment by fbjork** [comment]
Try running `npx grafbase@latest init --config-format typescript`

**Comment by mdamapong** [comment]
@fbjork Thank you for your reply. Still receive the following massage

`Need to install the following packages:
  grafbase@0.26.0
Ok to proceed? (y) y
/Users/mickeydamapong/.npm/_npx/694971729232e1da/node_modules/.bin/grafbase: line 1: This: command not found`

**Comment by fbjork** [comment]
> @fbjork Thank you for your reply. Still receive the following massage
> 
> 
> 
> `Need to install the following packages:
> 
>   grafbase@0.26.0
> 
> Ok to proceed? (y) y
> 
> /Users/mickeydamapong/.npm/_npx/694971729232e1da/node_modules/.bin/grafbase: line 1: This: command not found` 

Can you send the error message from the original issue running with npx?

**Comment by mdamapong** [comment]
My original error massage I got while running `npx grafbase init --config-format typescript
` 
`/Users/mickeydamapong/.npm/_npx/694971729232e1da/node_modules/.bin/grafbase: line 1: This: command not found`

**Comment by mdamapong** [comment]
@fbjork Thank you for your help. I didn't figure out what was the problem but I wipe my machine and was able to get it too work.

**Comment by rasyaFM** [comment]
> Try running `npx grafbase@latest init --config-format typescript`


i'm trying in my terminal but the result :

npx grafbase@latest init --config-format typescript
error: unexpected argument '--config-format' found

  tip: to pass '--config-format' as a value, use '-- --config-format'

Usage: grafbase init [OPTIONS] [NAME]

For more information, try '--help'.
