### ISSUE TITLE
Dark text on dark background

### ISSUE THREAD

**Issue by rafrafek** [grafbase/grafbase#567]
Text is hard to read - pricing page 
![IMG_1071](https://github.com/grafbase/grafbase/assets/23004737/0aa17270-a9a5-49cc-80a5-3b7f709d1bd6)

latest iOS, iPhone SE 3rd gen, Safari 

Website should use system theme, light in my case, and auto switch to dark when system switches to dark.

**Comment by vitalikda** [comment]
@rafrafek thanks for flagging that bug about the unreadable text! 🐛 Good news, we've already rolled out the fix and it's live now! 👍

About the second issue, unfortunately, our marketing website is all about that dark mode life, so changing themes based on your system isn't going to work 🌚 

However, our dashboard has got your back with both dark and light themes to choose from! 🌞🌚 The theme switcher is available under user's avatar in the top right corner 👌 

But hey, if you spot any other problems or have cool ideas to make our website even better, just hit us up on [Discord](https://discord.gg/grafbase). We're all ears!
