### ISSUE TITLE
Custom Queries

### ISSUE THREAD

**Issue by tecoad** [grafbase/grafbase#83]
Hi.

Sorry for this channel. I couldn't find any community for asking (Discord or Slack) would be great.

Isn't Grafbase really ready for custom queries?

I tried to create a simple 

type Query {
  images(user: String!): Image
}

But the Server cannot be reached on CLI.

Also, I think we need improved documentation for better understanding and more workable examples.

But it all seems very promissing!

**Comment by notrab** [comment]
Hey @tecoad 

Thanks for opening an issue to discuss the issues you're having.

Grafbase automatically creates the types for queries and mutations. All you need to define is the models you want APIs for. I've just today updated the documentation [Queries](https://grafbase.com/docs/reference/queries) and [Mutations](https://grafbase.com/docs/reference/mutations), which should help here. You can also see all of the scalars and types available to your schema [here](https://grafbase.com/docs/reference/schema).

I think [this document](https://grafbase.com/docs/getting-started/first-use) and [this tutorial](https://dev.to/notrab/instant-serverless-graphql-backends-with-grafbase-5g4o) might help getting you started.

We're working to improve our documentation and guides to make this experience great for everyone.

I'll close this issue but feel free to keep the conversation going if you have any more issues here, or over on [Discord](https://discord.gg/grafbase)
